name: Build and Upload Release Assets

on:
  push:
    tags:
      - '*'

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Build Release Assets
        run: npm run build
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: VideoDestroyer V${{ github.ref_name }}
          body: ${{needs.changelog.outputs.changelog}}
          draft: false
          files: ./dist/VideoDestroyer*
          token: ${{ github.token }}